apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ss-utopia-gateway
  name: ss-utopia-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ss-utopia-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: ss-utopia-gateway
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://ss-utopia-eureka:8761/eureka/
        image: 422288715120.dkr.ecr.us-east-1.amazonaws.com/ss-utopia-gateway:latest
        #image: jbnilles/test-gateway6:latest
        imagePullPolicy: ""
        name: ss-utopia-gateway
        ports:
        - containerPort: 8443
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ss-utopia-gateway
  name: ss-utopia-gateway
spec:
  type: LoadBalancer
  ports:
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    io.kompose.service: ss-utopia-gateway
status:
  loadBalancer: {}

